version: '3'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    volumes:
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: nopassword

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    links:
      - mysql:mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: nopassword
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
    depends_on:
      - mysql

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs:ro"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - ./nginx.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - reverse-proxy

  backups:
    image: christophetd/duplicacy-autobackup:v1.0
    container_name: backups
    restart: always
    environment:
      BACKUP_NAME: "${BACKUP_NAME}"
      BACKUP_LOCATION: "b2://${B2_BUCKET}"
      BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
      BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"
      B2_ID: "${B2_ID}"
      B2_KEY: "${B2_KEY}"
    volumes:
      - "${DATA_DIR}:/data"